// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wckiqeafyowjmkyblkez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja2lxZWFmeW93am1reWJsa2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTE0ODUsImV4cCI6MjA2NTQ2NzQ4NX0.cQGheV2BuSLpw9BAc0JnX_POUJqXDys_I-pL_6p7V7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);